[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
water_conservation = "CYgCc27FKtjZBwkDjeZ6VfyiifvbdBv9e9Q8Zn872jAK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# comprehensive-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/comprehensive/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
