[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
water_conservation = "9xaLoQx2x1xaum16rXQkPwpCsKbgErGqyXVrJstzD6Ff"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
comprehensive-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/comprehensive/**/*.ts"
